In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel("Dataset for Data Analytics.xlsx")

In [ ]:
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

In [ ]:
df.shape

(1200, 14)

In [ ]:
df.columns

Index(['OrderID', 'Date', 'CustomerID', 'Product', 'Quantity', 'UnitPrice',
       'ShippingAddress', 'PaymentMethod', 'OrderStatus', 'TrackingNumber',
       'ItemsInCart', 'CouponCode', 'ReferralSource', 'TotalPrice'],
      dtype='object')

In [ ]:
df.isnull().sum()

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df["OrderID"].duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

In [ ]:
df["CouponCode"] = df["CouponCode"].fillna("No Coupon")

In [ ]:
df.isnull().sum()

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

In [ ]:
df.dtypes

OrderID                    object
Date               datetime64[ns]
CustomerID                 object
Product                    object
Quantity                    int64
UnitPrice                 float64
ShippingAddress            object
PaymentMethod              object
OrderStatus                object
TrackingNumber             object
ItemsInCart                 int64
CouponCode                 object
ReferralSource             object
TotalPrice                float64
dtype: object

In [ ]:
df["Date"] = pd.to_datetime(df["Date"])

In [ ]:
df["Date"].dtype

dtype('<M8[ns]')

In [ ]:
df["Date"] = df["Date"].dt.strftime("%Y-%m-%d")

In [ ]:
df[["Quantity", "UnitPrice", "ItemsInCart", "TotalPrice"]].dtypes

Quantity         int64
UnitPrice      float64
ItemsInCart      int64
TotalPrice     float64
dtype: object

In [ ]:
print("Duplicate Rows:", df.duplicated().sum())
print("Duplicate Order IDs:", df["OrderID"].duplicated().sum())
print("Missing Values:")
print(df.isnull().sum())

Duplicate Rows: 0
Duplicate Order IDs: 0
Missing Values:
OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

# **Title**
# Project 1: Data Cleaning & Preparation

## Internship: DecodeLabs Data Analytics Internship

### Objective
The objective of this project is to clean a raw dataset by identifying missing values, removing duplicate records, correcting data formats, and preparing the dataset for further analysis.**bold text**

# **Before Loading Data**
## Step 1: Import Required Libraries

In this step, we import the required Python libraries for data analysis.
- Pandas: Used for data manipulation.
- NumPy: Used for numerical operations.

# **Loading Dataset**
## Step 2: Load Dataset

The dataset is loaded into a Pandas DataFrame using the read_excel() function.

# **Exploring Dataset**
## Step 3: Explore Dataset

The dataset is explored using:
- head()
- info()
- shape
- columns

This helps us understand the structure of the dataset.

# **Data Cleaning**
## Step 4: Data Cleaning

The following cleaning operations were performed:

- Checked duplicate rows
- Removed duplicate rows
- Checked duplicate Order IDs
- Identified missing values
- Filled missing CouponCode values
- Verified data types
- Standardized the Date column

In [ ]:
df.to_csv("Cleaned_Dataset.csv",index=False)

# **Results**

After cleaning:

- Duplicate Rows = 0
- Duplicate Order IDs = 0
- Missing Values = 0
- Date format standardized
- Dataset ready for analysis

In [ ]:
df.to_excel("Cleaned_Dataset.xlsx", index=False)

In [ ]:
print("=" * 40)
print("PROJECT 1 VERIFICATION")
print("=" * 40)

print("\nDataset Shape:")
print(df.shape)

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nDuplicate Order IDs:")
print(df["OrderID"].duplicated().sum())

print("\nMissing Values:")
print(df.isnull().sum())

print("\nData Types:")
print(df.dtypes)

print("\nProject 1 Completed Successfully!")

========================================
PROJECT 1 VERIFICATION
========================================

Dataset Shape:
(1200, 14)

Duplicate Rows:
0

Duplicate Order IDs:
0

Missing Values:
OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

Data Types:
OrderID             object
Date                object
CustomerID          object
Product             object
Quantity             int64
UnitPrice          float64
ShippingAddress     object
PaymentMethod       object
OrderStatus         object
TrackingNumber      object
ItemsInCart          int64
CouponCode          object
ReferralSource      object
TotalPrice         float64
dtype: object

Project 1 Completed Successfully!